<a href="https://colab.research.google.com/github/firewaterblood26-debug/Credit_Card_Fraud_Detection/blob/main/Credit_card_fraud_detection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the training dataset
train_df = pd.read_csv('/content/fraudtrain.csv')

# Load the testing dataset, skipping malformed lines
test_df = pd.read_csv('/content/fraudTest.csv', engine='python', on_bad_lines='skip')

print("Training Data Head:")
display(train_df.head())

print("\nTesting Data Head:")
display(test_df.head())

Training Data Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,1/1/2019 0:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",3/9/1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0.0
1,1,1/1/2019 0:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,6/21/1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0.0
2,2,1/1/2019 0:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1/19/1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0.0
3,3,1/1/2019 0:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1/12/1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0.0
4,4,1/1/2019 0:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,3/28/1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0.0

Testing Data Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1.371817e+09,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.436,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1.371817e+09,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.371817e+09,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1.371817e+09,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.01700000000001,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1.371817e+09,44.959148,-85.884734,0.0

In [ ]:
print("Missing values in training data:")
missing_train = train_df.isnull().sum()
missing_train = missing_train[missing_train > 0]
missing_train_percent = (missing_train / len(train_df)) * 100
missing_train_df = pd.DataFrame({
    'Missing Count': missing_train,
    'Missing Percentage': missing_train_percent
}).sort_values(by='Missing Percentage', ascending=False)
display(missing_train_df)

print("\nMissing values in testing data:")
missing_test = test_df.isnull().sum()
missing_test = missing_test[missing_test > 0]
missing_test_percent = (missing_test / len(test_df)) * 100
missing_test_df = pd.DataFrame({
    'Missing Count': missing_test,
    'Missing Percentage': missing_test_percent
}).sort_values(by='Missing Percentage', ascending=False)
display(missing_test_df)

Missing values in training data:

          Missing Count  Missing Percentage
is_fraud              1            0.000972

Missing values in testing data:

            Missing Count  Missing Percentage
is_fraud               15            0.011693
merch_long             14            0.010913
merch_lat              12            0.009354
unix_time              12            0.009354
trans_num              11            0.008575
dob                     9            0.007016
job                     9            0.007016
city_pop                8            0.006236
long                    8            0.006236
lat                     7            0.005457
zip                     6            0.004677
state                   3            0.002339
city                    3            0.002339
street                  2            0.001559
gender                  2            0.001559
last                    2            0.001559
first                   1            0.000780

In [ ]:
print(f"Shape of train_df before dropping missing values: {train_df.shape}")
train_df.dropna(inplace=True)
print(f"Shape of train_df after dropping missing values: {train_df.shape}")

print(f"\nShape of test_df before dropping missing values: {test_df.shape}")
test_df.dropna(inplace=True)
print(f"Shape of test_df after dropping missing values: {test_df.shape}")

Shape of train_df before dropping missing values: (102880, 23)
Shape of train_df after dropping missing values: (102880, 23)

Shape of test_df before dropping missing values: (128271, 23)
Shape of test_df after dropping missing values: (128271, 23)

In [ ]:
print('Converting trans_date_trans_time to datetime objects...')
train_df['trans_date_trans_time'] = pd.to_datetime(train_df['trans_date_trans_time'])
test_df['trans_date_trans_time'] = pd.to_datetime(test_df['trans_date_trans_time'])

print('\nData types after conversion for train_df:')
display(train_df[['trans_date_trans_time']].info())

print('\nData types after conversion for test_df:')
display(test_df[['trans_date_trans_time']].info())

Converting trans_date_trans_time to datetime objects...

Data types after conversion for train_df:
<class 'pandas.core.frame.DataFrame'>
Index: 102880 entries, 0 to 102879
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  102880 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.6 MB

None

Data types after conversion for test_df:
<class 'pandas.core.frame.DataFrame'>
Index: 128271 entries, 0 to 128284
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  128271 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 2.0 MB

None

### Feature Engineering: Extracting Time-Based Features

In [ ]:
print('Extracting time-based features from trans_date_trans_time...')

def extract_time_features(df):
    df['year'] = df['trans_date_trans_time'].dt.year
    df['month'] = df['trans_date_trans_time'].dt.month
    df['day'] = df['trans_date_trans_time'].dt.day
    df['hour'] = df['trans_date_trans_time'].dt.hour
    df['minute'] = df['trans_date_trans_time'].dt.minute
    df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
    df['week_of_year'] = df['trans_date_trans_time'].dt.isocalendar().week.astype(int)
    df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
    return df

train_df = extract_time_features(train_df)
test_df = extract_time_features(test_df)

print('\nFirst 5 rows of train_df with new time features:')
display(train_df.head())

print('\nFirst 5 rows of test_df with new time features:')
display(test_df.head())

Extracting time-based features from trans_date_trans_time...

First 5 rows of train_df with new time features:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,merch_long,is_fraud,year,month,day,hour,minute,day_of_week,week_of_year,is_weekend
0,0,2019-01-01 00:00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-82.048315,0.0,2019,1,1,0,0,1,1,0
1,1,2019-01-01 00:00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.186462,0.0,2019,1,1,0,0,1,1,0
2,2,2019-01-01 00:00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.154481,0.0,2019,1,1,0,0,1,1,0
3,3,2019-01-01 00:01:00,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.561071,0.0,2019,1,1,0,1,1,1,0
4,4,2019-01-01 00:03:00,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-78.632459,0.0,2019,1,1,0,3,1,1,0

First 5 rows of test_df with new time features:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,merch_long,is_fraud,year,month,day,hour,minute,day_of_week,week_of_year,is_weekend
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,-81.200714,0.0,2020,6,21,12,14,6,25,1
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,-109.960431,0.0,2020,6,21,12,14,6,25,1
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,-74.196111,0.0,2020,6,21,12,14,6,25,1
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,-80.883061,0.0,2020,6,21,12,15,6,25,1
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,-85.884734,0.0,2020,6,21,12,15,6,25,1

### Data Preprocessing: Handling Categorical Features

In [ ]:
print('Identifying and encoding categorical features...')

# Identify categorical columns (excluding the target variable 'is_fraud')
categorical_cols = [
    col for col in train_df.select_dtypes(include='object').columns
    if col != 'is_fraud'
]

print(f"Categorical columns to encode: {categorical_cols}")

# Apply one-hot encoding
train_df = pd.get_dummies(train_df, columns=categorical_cols, drop_first=True)
test_df = pd.get_dummies(test_df, columns=categorical_cols, drop_first=True)

print(f"Shape of train_df after one-hot encoding: {train_df.shape}")
print(f"Shape of test_df after one-hot encoding: {test_df.shape}")

print('\nTrain_df head after one-hot encoding:')
display(train_df.head())

print('\nTest_df head after one-hot encoding:')
display(test_df.head())

Identifying and encoding categorical features...
Categorical columns to encode: ['merchant', 'category', 'gender', 'city', 'state', 'job']
Shape of train_df after one-hot encoding: (102880, 2096)
Shape of test_df after one-hot encoding: (128271, 2084)

Train_df head after one-hot encoding:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Video editor,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
0,4.97,28654,36.0788,-81.1781,3495,36.011293,-82.048315,0.0,2019,1,...,False,False,False,False,False,False,False,False,False,False
1,107.23,99160,48.8878,-118.2105,149,49.159047,-118.186462,0.0,2019,1,...,False,False,False,False,False,False,False,False,False,False
2,220.11,83252,42.1808,-112.2620,4154,43.150704,-112.154481,0.0,2019,1,...,False,False,False,False,False,False,False,False,False,False
3,45.00,59632,46.2306,-112.1138,1939,47.034331,-112.561071,0.0,2019,1,...,False,False,False,False,False,False,False,False,False,False
4,41.96,24433,38.4207,-79.4629,99,38.674999,-78.632459,0.0,2019,1,...,False,False,False,False,False,False,False,False,False,False

Test_df head after one-hot encoding:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Video editor,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
0,2.86,29209,33.9659,-80.9355,333497,33.986391,-81.200714,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
1,29.84,84002,40.3207,-110.436,302,39.450498,-109.960431,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
2,41.28,11710,40.6729,-73.5365,34496,40.495810,-74.196111,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
3,60.05,32780,28.5697,-80.8191,54767,28.812398,-80.883061,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
4,3.19,49632,44.2529,-85.01700000000001,1126,44.959148,-85.884734,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False

### Aligning Columns After One-Hot Encoding

In [ ]:
print('Aligning columns between train_df and test_df...')

# Get all columns from both dataframes
train_cols = set(train_df.columns)
test_cols = set(test_df.columns)

# Identify columns unique to train_df and test_df
missing_in_test = list(train_cols - test_cols)
missing_in_train = list(test_cols - train_cols)

# Add missing columns to test_df and fill with 0
for col in missing_in_test:
    test_df[col] = 0

# Add missing columns to train_df and fill with 0
for col in missing_in_train:
    train_df[col] = 0

# Ensure the order of columns is the same
test_df = test_df[train_df.columns]

print(f"Shape of train_df after alignment: {train_df.shape}")
print(f"Shape of test_df after alignment: {test_df.shape}")

print('\nTrain_df head after alignment:')
display(train_df.head())

print('\nTest_df head after alignment:')
display(test_df.head())

Aligning columns between train_df and test_df...
Shape of train_df after alignment: (102880, 2100)
Shape of test_df after alignment: (128271, 2100)

Train_df head after alignment:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,4.97,28654,36.0788,-81.1781,3495,36.011293,-82.048315,0.0,2019,1,...,False,False,False,False,False,False,0,0,0,0
1,107.23,99160,48.8878,-118.2105,149,49.159047,-118.186462,0.0,2019,1,...,False,False,False,False,False,False,0,0,0,0
2,220.11,83252,42.1808,-112.2620,4154,43.150704,-112.154481,0.0,2019,1,...,False,False,False,False,False,False,0,0,0,0
3,45.00,59632,46.2306,-112.1138,1939,47.034331,-112.561071,0.0,2019,1,...,False,False,False,False,False,False,0,0,0,0
4,41.96,24433,38.4207,-79.4629,99,38.674999,-78.632459,0.0,2019,1,...,False,False,False,False,False,False,0,0,0,0

Test_df head after alignment:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,2.86,29209,33.9659,-80.9355,333497,33.986391,-81.200714,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
1,29.84,84002,40.3207,-110.436,302,39.450498,-109.960431,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
2,41.28,11710,40.6729,-73.5365,34496,40.495810,-74.196111,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
3,60.05,32780,28.5697,-80.8191,54767,28.812398,-80.883061,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False
4,3.19,49632,44.2529,-85.01700000000001,1126,44.959148,-85.884734,0.0,2020,6,...,False,False,False,False,False,False,False,False,False,False

### Data Preprocessing: Dropping Irrelevant Columns

In [ ]:
print('Dropping irrelevant columns...')

# Columns to drop based on being identifiers or already processed
columns_to_drop = [
    'Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'first', 'last',
    'street', 'trans_num', 'unix_time', 'dob'
]

train_df.drop(columns=columns_to_drop, inplace=True)
test_df.drop(columns=columns_to_drop, inplace=True)

print(f"Shape of train_df after dropping columns: {train_df.shape}")
print(f"Shape of test_df after dropping columns: {test_df.shape}")

print('\nTrain_df head after dropping columns:')
display(train_df.head())

print('\nTest_df head after dropping columns:')
display(test_df.head())

Dropping irrelevant columns...
Shape of train_df after dropping columns: (102880, 22)
Shape of test_df after dropping columns: (128271, 22)

Train_df head after dropping columns:

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,...,merch_long,is_fraud,year,month,day,hour,minute,day_of_week,week_of_year,is_weekend
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,36.0788,-81.1781,3495,...,-82.048315,0.0,2019,1,1,0,0,1,1,0
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,48.8878,-118.2105,149,...,-118.186462,0.0,2019,1,1,0,0,1,1,0
2,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,42.1808,-112.2620,4154,...,-112.154481,0.0,2019,1,1,0,0,1,1,0
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,46.2306,-112.1138,1939,...,-112.561071,0.0,2019,1,1,0,1,1,1,0
4,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,38.4207,-79.4629,99,...,-78.632459,0.0,2019,1,1,0,3,1,1,0

Test_df head after dropping columns:

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,...,merch_long,is_fraud,year,month,day,hour,minute,day_of_week,week_of_year,is_weekend
0,fraud_Kirlin and Sons,personal_care,2.86,M,Columbia,SC,29209,33.9659,-80.9355,333497,...,-81.200714,0.0,2020,6,21,12,14,6,25,1
1,fraud_Sporer-Keebler,personal_care,29.84,F,Altonah,UT,84002,40.3207,-110.436,302,...,-109.960431,0.0,2020,6,21,12,14,6,25,1
2,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,Bellmore,NY,11710,40.6729,-73.5365,34496,...,-74.196111,0.0,2020,6,21,12,14,6,25,1
3,fraud_Haley Group,misc_pos,60.05,M,Titusville,FL,32780,28.5697,-80.8191,54767,...,-80.883061,0.0,2020,6,21,12,15,6,25,1
4,fraud_Johnston-Casper,travel,3.19,M,Falmouth,MI,49632,44.2529,-85.01700000000001,1126,...,-85.884734,0.0,2020,6,21,12,15,6,25,1

### Data Preprocessing: Scaling Numerical Features

In [ ]:
from sklearn.preprocessing import StandardScaler

print('Scaling numerical features...')

# Identify numerical columns (excluding the target variable 'is_fraud' and boolean columns from one-hot encoding)
numerical_cols = train_df.select_dtypes(include=['int64', 'float64']).columns.tolist()
if 'is_fraud' in numerical_cols:
    numerical_cols.remove('is_fraud')

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to numerical columns in both train_df and test_df
train_df[numerical_cols] = scaler.fit_transform(train_df[numerical_cols])
test_df[numerical_cols] = scaler.transform(test_df[numerical_cols])

print('\nFirst 5 rows of train_df after scaling numerical features:')
display(train_df.head())

print('\nFirst 5 rows of test_df after scaling numerical features:')
display(test_df.head())

Scaling numerical features...

First 5 rows of train_df after scaling numerical features:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,-0.459250,-0.745633,-0.484483,0.653195,-0.284143,-0.494745,0.589574,0.0,2019,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
1,0.242064,1.876243,2.038290,-2.035811,-0.295232,2.077995,-2.032311,0.0,2019,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
2,1.016212,1.284679,0.717325,-1.603877,-0.281958,0.902288,-1.594681,0.0,2019,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
3,-0.184719,0.406333,1.514946,-1.593116,-0.289299,1.662233,-1.624179,0.0,2019,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
4,-0.205567,-0.902597,-0.023239,0.777739,-0.295397,0.026487,0.837400,0.0,2019,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0

First 5 rows of test_df after scaling numerical features:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,-0.473721,-0.724994,-0.900626,0.670811,0.809527,-0.890975,0.651069,0.0,2020,6,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
1,-0.288688,1.312569,0.350972,-1.471287,-0.294725,0.178236,-1.435498,0.0,2020,6,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
2,-0.210231,-1.375722,0.420339,1.208068,-0.181401,0.382781,1.159265,0.0,2020,6,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
3,-0.081503,-0.592201,-1.963424,0.679263,-0.114220,-1.903417,0.674115,0.0,2020,6,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
4,-0.471458,0.034467,1.125432,0.374444,-0.291994,1.256163,0.311235,0.0,2020,6,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0

### Preparing Data for Modeling: Splitting Features and Target

In [ ]:
print('Splitting data into features (X) and target (y)...')

X_train = train_df.drop('is_fraud', axis=1)
y_train = train_df['is_fraud']

X_test = test_df.drop('is_fraud', axis=1)
y_test = test_df['is_fraud']

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

print('\nFirst 5 rows of X_train:')
display(X_train.head())

print('\nFirst 5 rows of y_train:')
display(y_train.head())

Splitting data into features (X) and target (y)...
Shape of X_train: (102880, 2099)
Shape of y_train: (102880,)
Shape of X_test: (128271, 2099)
Shape of y_test: (128271,)

First 5 rows of X_train:

,amt,zip,lat,long,city_pop,merch_lat,merch_long,year,month,day,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,-0.459250,-0.745633,-0.484483,0.653195,-0.284143,-0.494745,0.589574,2019,1,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
1,0.242064,1.876243,2.038290,-2.035811,-0.295232,2.077995,-2.032311,2019,1,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
2,1.016212,1.284679,0.717325,-1.603877,-0.281958,0.902288,-1.594681,2019,1,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
3,-0.184719,0.406333,1.514946,-1.593116,-0.289299,1.662233,-1.624179,2019,1,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0
4,-0.205567,-0.902597,-0.023239,0.777739,-0.295397,0.026487,0.837400,2019,1,1,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0

First 5 rows of y_train:

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: is_fraud, dtype: float64

In [ ]:
print('Initializing and training Logistic Regression model...')

from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression model with class_weight='balanced' to handle imbalance
log_reg = LogisticRegression(class_weight='balanced', solver='liblinear', random_state=42)

# Train the model
log_reg.fit(X_train, y_train)

print('Logistic Regression model trained successfully.')

Initializing and training Logistic Regression model...
Logistic Regression model trained successfully.

In [ ]:
print('Evaluating Logistic Regression model performance...')

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Make predictions on the test set
y_pred = log_reg.predict(X_test)
y_pred_proba = log_reg.predict_proba(X_test)[:, 1]  # Probabilities for the positive class

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"\nAccuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

Evaluating Logistic Regression model performance...

Accuracy: 0.9570
Precision: 0.0146
Recall: 0.1426
F1-Score: 0.0265
ROC AUC: 0.7608

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98    127745
         1.0       0.01      0.14      0.03       526

    accuracy                           0.96    128271
   macro avg       0.51      0.55      0.50    128271
weighted avg       0.99      0.96      0.97    128271


Confusion Matrix:
[[122682   5063]
 [   451     75]]

In [ ]:
print('Initializing and training Random Forest model...')

from sklearn.ensemble import RandomForestClassifier

# Initialize Random Forest classifier with class_weight='balanced'
# n_estimators can be adjusted, but 100 is a good starting point
# random_state for reproducibility
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42, n_jobs=-1)

# Train the model
rf_model.fit(X_train, y_train)

print('Random Forest model trained successfully.')

Initializing and training Random Forest model...
Random Forest model trained successfully.

In [ ]:
print('Evaluating Random Forest model performance...')

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)
y_pred_proba_rf = rf_model.predict_proba(X_test)[:, 1]  # Probabilities for the positive class

# Calculate evaluation metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_auc_rf = roc_auc_score(y_test, y_pred_proba_rf)

print(f"\nRandom Forest Accuracy: {accuracy_rf:.4f}")
print(f"Random Forest Precision: {precision_rf:.4f}")
print(f"Random Forest Recall: {recall_rf:.4f}")
print(f"Random Forest F1-Score: {f1_rf:.4f}")
print(f"Random Forest ROC AUC: {roc_auc_rf:.4f}")

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

print("\nRandom Forest Confusion Matrix:")
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

Evaluating Random Forest model performance...

Random Forest Accuracy: 0.9961
Random Forest Precision: 1.0000
Random Forest Recall: 0.0608
Random Forest F1-Score: 0.1147
Random Forest ROC AUC: 0.9175

Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    127745
         1.0       1.00      0.06      0.11       526

    accuracy                           1.00    128271
   macro avg       1.00      0.53      0.56    128271
weighted avg       1.00      1.00      0.99    128271


Random Forest Confusion Matrix:
[[127745      0]
 [   494     32]]

In [ ]:
print('Adjusting Random Forest classification threshold and re-evaluating...')

# Define the new threshold
new_threshold = 0.2

# Apply the new threshold to the predicted probabilities
y_pred_rf_threshold = (y_pred_proba_rf >= new_threshold).astype(int)

# Calculate evaluation metrics with the new threshold
accuracy_rf_thresh = accuracy_score(y_test, y_pred_rf_threshold)
precision_rf_thresh = precision_score(y_test, y_pred_rf_threshold)
recall_rf_thresh = recall_score(y_test, y_pred_rf_threshold)
f1_rf_thresh = f1_score(y_test, y_pred_rf_threshold)

# ROC AUC does not change with threshold adjustment, as it uses probabilities directly
roc_auc_rf_thresh = roc_auc_score(y_test, y_pred_proba_rf)

print(f"\nRandom Forest Accuracy (Threshold={new_threshold}): {accuracy_rf_thresh:.4f}")
print(f"Random Forest Precision (Threshold={new_threshold}): {precision_rf_thresh:.4f}")
print(f"Random Forest Recall (Threshold={new_threshold}): {recall_rf_thresh:.4f}")
print(f"Random Forest F1-Score (Threshold={new_threshold}): {f1_rf_thresh:.4f}")
print(f"Random Forest ROC AUC (Threshold={new_threshold}): {roc_auc_rf_thresh:.4f}")

print("\nRandom Forest Classification Report (Adjusted Threshold):")
print(classification_report(y_test, y_pred_rf_threshold))

print("\nRandom Forest Confusion Matrix (Adjusted Threshold):")
cm_rf_thresh = confusion_matrix(y_test, y_pred_rf_threshold)
print(cm_rf_thresh)

Adjusting Random Forest classification threshold and re-evaluating...

Random Forest Accuracy (Threshold=0.2): 0.9960
Random Forest Precision (Threshold=0.2): 0.5177
Random Forest Recall (Threshold=0.2): 0.4449
Random Forest F1-Score (Threshold=0.2): 0.4785
Random Forest ROC AUC (Threshold=0.2): 0.9175

Random Forest Classification Report (Adjusted Threshold):
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    127745
         1.0       0.52      0.44      0.48       526

    accuracy                           1.00    128271
   macro avg       0.76      0.72      0.74    128271
weighted avg       1.00      1.00      1.00    128271


Random Forest Confusion Matrix (Adjusted Threshold):
[[127527    218]
 [   292    234]]

### Hyperparameter Tuning for Random Forest using GridSearchCV

In [ ]:
print('Starting GridSearchCV for Random Forest hyperparameter tuning...')

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [10, 20, None], # None means nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'class_weight': ['balanced'] # Keep balanced for imbalanced dataset
}

# Initialize a Random Forest Classifier
rf_base = RandomForestClassifier(random_state=42, n_jobs=-1)

# Initialize GridSearchCV
# Scoring 'recall' is chosen to prioritize identifying more fraudulent transactions
grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    scoring='recall',
    cv=3, # Using 3-fold cross-validation for faster execution, can be increased for more robust results
    verbose=2,
    n_jobs=-1
)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

print('\nGridSearchCV completed.')
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best recall score found: {grid_search.best_score_:.4f}")

Starting GridSearchCV for Random Forest hyperparameter tuning...
Fitting 3 folds for each of 24 candidates, totalling 72 fits

GridSearchCV completed.
Best parameters found: {'class_weight': 'balanced', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 50}
Best recall score found: 0.6969

In [ ]:
print('Evaluating the best Random Forest model found by GridSearchCV...')

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Get the best model from GridSearchCV
best_rf_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
y_pred_best_rf = best_rf_model.predict(X_test)
y_pred_proba_best_rf = best_rf_model.predict_proba(X_test)[:, 1] # Probabilities for the positive class

# Calculate evaluation metrics
accuracy_best_rf = accuracy_score(y_test, y_pred_best_rf)
precision_best_rf = precision_score(y_test, y_pred_best_rf)
recall_best_rf = recall_score(y_test, y_pred_best_rf)
f1_best_rf = f1_score(y_test, y_pred_best_rf)
roc_auc_best_rf = roc_auc_score(y_test, y_pred_proba_best_rf)

print(f"\nBest Random Forest Accuracy: {accuracy_best_rf:.4f}")
print(f"Best Random Forest Precision: {precision_best_rf:.4f}")
print(f"Best Random Forest Recall: {recall_best_rf:.4f}")
print(f"Best Random Forest F1-Score: {f1_best_rf:.4f}")
print(f"Best Random Forest ROC AUC: {roc_auc_best_rf:.4f}")

print("\nBest Random Forest Classification Report:")
print(classification_report(y_test, y_pred_best_rf))

print("\nBest Random Forest Confusion Matrix:")
cm_best_rf = confusion_matrix(y_test, y_pred_best_rf)
print(cm_best_rf)

Evaluating the best Random Forest model found by GridSearchCV...

Best Random Forest Accuracy: 0.9751
Best Random Forest Precision: 0.1042
Best Random Forest Recall: 0.6673
Best Random Forest F1-Score: 0.1802
Best Random Forest ROC AUC: 0.9037

Best Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99    127745
         1.0       0.10      0.67      0.18       526

    accuracy                           0.98    128271
   macro avg       0.55      0.82      0.58    128271
weighted avg       0.99      0.98      0.98    128271


Best Random Forest Confusion Matrix:
[[124727   3018]
 [   175    351]]

### Deploying the Model: Saving the Trained Model

In [ ]:
import joblib
import os

# Define the filename for the saved model
model_filename = 'best_random_forest_fraud_detector.joblib'

# Save the best model to disk
joblib.dump(best_rf_model, model_filename)

print(f"Best Random Forest model saved to {model_filename}")
print(f"Model size: {os.path.getsize(model_filename) / (1024 * 1024):.2f} MB")

Best Random Forest model saved to best_random_forest_fraud_detector.joblib
Model size: 0.41 MB

### Loading the Model for Inference (Example)

Once saved, you can load the model in a new environment or application to make predictions on new data. Here's how you would load it and make a sample prediction:

In [ ]:
import joblib
import pandas as pd

# Load the saved model
loaded_model = joblib.load('best_random_forest_fraud_detector.joblib')

print("Model loaded successfully!")

# Example of making a prediction on a new data point (using the first row of X_test for demonstration)
# In a real-world scenario, you would preprocess new incoming data in the same way as the training data

# Ensure the input data has the same features and order as the training data
sample_new_data = X_test.iloc[[0]] # Using iloc[[0]] to keep it as a DataFrame

# Make a prediction
prediction = loaded_model.predict(sample_new_data)
prediction_proba = loaded_model.predict_proba(sample_new_data)[:, 1]

print(f"\nSample New Data (first row of X_test):")
display(sample_new_data)
print(f"Prediction for sample_new_data: {prediction[0]} (0: Not Fraud, 1: Fraud)")
print(f"Probability of Fraud for sample_new_data: {prediction_proba[0]:.4f}")

Model loaded successfully!

Sample New Data (first row of X_test):

,amt,zip,lat,long,city_pop,merch_lat,merch_long,year,month,day,...,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer,city_Springville,city_Rice,"job_Engineer, water",city_Grifton
0,-0.473721,-0.724994,-0.900626,0.670811,0.809527,-0.890975,0.651069,2020,6,21,...,False,False,False,False,False,False,0.0,0.0,0.0,0.0

Prediction for sample_new_data: 0.0 (0: Not Fraud, 1: Fraud)
Probability of Fraud for sample_new_data: 0.3618